server:
  port: 9003
spring:
  application:
    name: service-article

com:
  madao:
    aopPointcutExpression: execution (* com.madao.article..*.*(..))

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false
        isolation:
          strategy: SEMAPHORE