server:
  port: 9007
spring:
  application:
    name: service-user
  boot:
    admin:
      client:
        instance:
          service-base-url: http://localhost:9007

com:
  madao:
    aopPointcutExpression: execution (* com.madao.user..*.*(..))

