server:
  port: 9006
spring:
  application:
    name: service-search #指定服务名
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 39.108.191.56:9300



eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
      defaultZone:  http://localhost:5000/eureka  #单机版
  instance:
    instance-id: ${spring.cloud.client.ip-address}:${server.port} # 为注册的这个服务起个别名
    prefer-ip-address: true     #使用ip进行注册
    # 注册中心跳转到swagger接口
    status-page-url-path:  /swagger-ui.html
    # #绑定客户端的ip而不是主机号
    hostname: ${spring.cloud.client.ip-address}   # ${spring.cloud.client.ip-address} 参考https://blog.csdn.net/xichenguan/article/details/76632033
